apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: rabbitmq-idempotency
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-postgres-secret
  namespace: rabbitmq-idempotency
type: Opaque
data:
  POSTGRES_DB: cGF5bWVudF9kYg==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-postgres-secret
  namespace: rabbitmq-idempotency
type: Opaque
data:
  POSTGRES_DB: bm90aWZpY2F0aW9uX2Ri
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=