apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: rabbitmq-idempotency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7071
          envFrom:
            - configMapRef:
                name: rabbit-mq-config
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7071
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7071
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: rabbitmq-idempotency
spec:
  selector:
    app: payment-service
  ports:
    - port: 7071
      targetPort: 7071
  type: NodePort