apiVersion: apps/v1
kind: Deployment
metadata:
  name: psp-mock-service
  namespace: rabbitmq-idempotency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psp-mock-service
  template:
    metadata:
      labels:
        app: psp-mock-service
    spec:
      containers:
        - name: psp-mock-service
          image: psp-mock-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7072
---
apiVersion: v1
kind: Service
metadata:
  name: psp-mock-service
  namespace: rabbitmq-idempotency
spec:
  selector:
    app: psp-mock-service
  ports:
    - port: 7072
      targetPort: 7072
  type: NodePort